version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      reviewed-actions:
        patterns:
          - "actions/*"
    open-pull-requests-limit: 5
