-- Generated by tools/render_ingestion_assets.py; do not edit by hand.
-- tools/ingestion_contract.py is the table, column, join, and query contract.
-- SQLite queries use named :service and :environment parameters.

CREATE TABLE IF NOT EXISTS resq_runs (
  run_id TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT NOT NULL,
  duration_seconds REAL NOT NULL,
  framework_version TEXT NOT NULL,
  hostname TEXT NOT NULL,
  q_version TEXT NOT NULL,
  os TEXT NOT NULL,
  test_count INTEGER NOT NULL,
  pass_count INTEGER NOT NULL,
  fail_count INTEGER NOT NULL,
  error_count INTEGER NOT NULL,
  skip_count INTEGER NOT NULL,
  assertion_count INTEGER NOT NULL,
  labels TEXT NOT NULL,
  environment TEXT NOT NULL,
  service TEXT NOT NULL,
  deployment_id TEXT NOT NULL,
  artifact_digest TEXT NOT NULL,
  vcs_sha TEXT NOT NULL,
  vcs_branch TEXT NOT NULL,
  ci_provider TEXT NOT NULL,
  ci_pipeline_id TEXT NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (run_id)
);
CREATE TABLE IF NOT EXISTS resq_tests (
  run_id TEXT NOT NULL,
  execution_id TEXT NOT NULL,
  test_id TEXT NOT NULL,
  case_id TEXT NOT NULL,
  suite TEXT NOT NULL,
  description TEXT NOT NULL,
  kind TEXT NOT NULL,
  status TEXT NOT NULL,
  duration_seconds REAL NOT NULL,
  asserts_run INTEGER NOT NULL,
  attempts INTEGER NOT NULL,
  retried INTEGER NOT NULL,
  flaky INTEGER NOT NULL,
  file_path TEXT NOT NULL,
  line INTEGER,
  message TEXT NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (run_id, execution_id),
  FOREIGN KEY (run_id) REFERENCES resq_runs (run_id)
);
CREATE TABLE IF NOT EXISTS resq_attempts (
  run_id TEXT NOT NULL,
  execution_id TEXT NOT NULL,
  attempt_key TEXT NOT NULL,
  attempt INTEGER NOT NULL,
  status TEXT NOT NULL,
  duration_seconds REAL NOT NULL,
  started_at TEXT,
  finished_at TEXT,
  asserts_run INTEGER NOT NULL,
  message TEXT NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (attempt_key),
  FOREIGN KEY (run_id, execution_id) REFERENCES resq_tests (run_id, execution_id)
);
CREATE TABLE IF NOT EXISTS resq_benchmarks (
  run_id TEXT NOT NULL,
  benchmark_id TEXT NOT NULL,
  test_id TEXT NOT NULL,
  suite TEXT NOT NULL,
  description TEXT NOT NULL,
  metric TEXT NOT NULL,
  unit TEXT NOT NULL,
  runs INTEGER NOT NULL,
  avg_time_ms REAL,
  med_time_ms REAL,
  max_time_ms REAL,
  avg_space_bytes REAL,
  comparison_class TEXT NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (run_id, benchmark_id),
  FOREIGN KEY (run_id) REFERENCES resq_runs (run_id)
);
CREATE TABLE IF NOT EXISTS resq_diagnostics (
  run_id TEXT NOT NULL,
  diagnostic_key TEXT NOT NULL,
  type TEXT NOT NULL,
  severity TEXT NOT NULL,
  phase TEXT NOT NULL,
  message TEXT NOT NULL,
  data TEXT NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (diagnostic_key),
  FOREIGN KEY (run_id) REFERENCES resq_runs (run_id)
);
CREATE TABLE IF NOT EXISTS resq_coverage_runs (
  run_id TEXT NOT NULL,
  functions_found INTEGER NOT NULL,
  functions_hit INTEGER NOT NULL,
  function_percent REAL NOT NULL,
  lines_found INTEGER NOT NULL,
  lines_hit INTEGER NOT NULL,
  line_percent REAL NOT NULL,
  statement_sites_found INTEGER NOT NULL,
  statement_sites_hit INTEGER NOT NULL,
  statement_site_percent REAL NOT NULL,
  statement_site_instrumentation_percent REAL NOT NULL,
  statement_site_instrumentation_complete INTEGER NOT NULL,
  branches_found INTEGER NOT NULL,
  branches_hit INTEGER NOT NULL,
  branch_percent REAL NOT NULL,
  branch_instrumentation_percent REAL NOT NULL,
  branch_instrumentation_complete INTEGER NOT NULL,
  function_instrumentation_percent REAL NOT NULL,
  statement_instrumentation_percent REAL NOT NULL,
  statement_instrumentation_complete INTEGER NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (run_id),
  FOREIGN KEY (run_id) REFERENCES resq_runs (run_id)
);
CREATE TABLE IF NOT EXISTS resq_coverage_files (
  run_id TEXT NOT NULL,
  coverage_file_key TEXT NOT NULL,
  file_path TEXT NOT NULL,
  loaded INTEGER NOT NULL,
  function_found INTEGER NOT NULL,
  function_hit INTEGER NOT NULL,
  line_found INTEGER NOT NULL,
  line_hit INTEGER NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (coverage_file_key),
  FOREIGN KEY (run_id) REFERENCES resq_runs (run_id)
);
CREATE TABLE IF NOT EXISTS resq_coverage_functions (
  run_id TEXT NOT NULL,
  coverage_file_key TEXT NOT NULL,
  coverage_function_key TEXT NOT NULL,
  file_path TEXT NOT NULL,
  function_name TEXT NOT NULL,
  line INTEGER NOT NULL,
  hits INTEGER NOT NULL,
  covered INTEGER NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (coverage_function_key),
  FOREIGN KEY (coverage_file_key) REFERENCES resq_coverage_files (coverage_file_key)
);
CREATE TABLE IF NOT EXISTS resq_coverage_sites (
  run_id TEXT NOT NULL,
  coverage_file_key TEXT NOT NULL,
  coverage_function_key TEXT NOT NULL,
  coverage_site_key TEXT NOT NULL,
  site_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  file_path TEXT NOT NULL,
  function_name TEXT NOT NULL,
  line INTEGER,
  column_number INTEGER,
  eligible INTEGER NOT NULL,
  instrumented INTEGER NOT NULL,
  hits INTEGER,
  edges_hit INTEGER,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (coverage_site_key),
  FOREIGN KEY (coverage_file_key) REFERENCES resq_coverage_files (coverage_file_key)
);
CREATE TABLE IF NOT EXISTS resq_coverage_edges (
  run_id TEXT NOT NULL,
  coverage_site_key TEXT NOT NULL,
  coverage_edge_key TEXT NOT NULL,
  edge_id TEXT NOT NULL,
  label TEXT NOT NULL,
  hits INTEGER NOT NULL,
  covered INTEGER NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (coverage_edge_key),
  FOREIGN KEY (coverage_site_key) REFERENCES resq_coverage_sites (coverage_site_key)
);
CREATE TABLE IF NOT EXISTS resq_coverage_contexts (
  run_id TEXT NOT NULL,
  coverage_context_key TEXT NOT NULL,
  context_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  test_id TEXT NOT NULL,
  attempt INTEGER NOT NULL,
  suite TEXT NOT NULL,
  description TEXT NOT NULL,
  file_path TEXT NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (coverage_context_key),
  FOREIGN KEY (run_id) REFERENCES resq_runs (run_id)
);
CREATE TABLE IF NOT EXISTS resq_coverage_context_metrics (
  run_id TEXT NOT NULL,
  coverage_context_key TEXT NOT NULL,
  metric_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  coverage_file_key TEXT NOT NULL,
  coverage_site_key TEXT NOT NULL,
  function_name TEXT NOT NULL,
  edge_index INTEGER,
  edge_label TEXT NOT NULL,
  hits INTEGER NOT NULL,
  raw_payload TEXT NOT NULL,
  PRIMARY KEY (run_id, coverage_context_key, metric_id),
  FOREIGN KEY (coverage_context_key) REFERENCES resq_coverage_contexts (coverage_context_key)
);

-- query:services — Services
SELECT DISTINCT service AS __text, service AS __value FROM resq_runs WHERE service <> '' ORDER BY service;

-- query:environments — Environments
SELECT DISTINCT environment AS __text, environment AS __value FROM resq_runs WHERE environment <> '' AND (:service = '' OR service = :service) ORDER BY environment;

-- query:pass_fail_rate — Pass/fail rate
SELECT r.finished_at AS time, r.service, r.environment,
       CASE WHEN r.test_count = 0 THEN 100.0 ELSE 100.0 * r.pass_count / r.test_count END AS pass_rate,
       r.fail_count + r.error_count AS failures
FROM resq_runs AS r WHERE (:service = '' OR r.service = :service) AND (:environment = '' OR r.environment = :environment) ORDER BY r.finished_at;

-- query:run_duration — Run duration
SELECT r.finished_at AS time, r.service, r.environment, r.duration_seconds
FROM resq_runs AS r WHERE (:service = '' OR r.service = :service) AND (:environment = '' OR r.environment = :environment) ORDER BY r.finished_at;

-- query:test_history — Per-test history
SELECT r.finished_at AS time, t.test_id, t.case_id, t.suite, t.description,
       t.status, t.duration_seconds, t.file_path
FROM resq_tests AS t JOIN resq_runs AS r ON r.run_id = t.run_id
WHERE (:service = '' OR r.service = :service) AND (:environment = '' OR r.environment = :environment) ORDER BY r.finished_at, t.test_id, t.case_id;

-- query:benchmark_history — Benchmark median/classification
SELECT r.finished_at AS time, b.benchmark_id, b.suite, b.description,
       b.med_time_ms, b.comparison_class
FROM resq_benchmarks AS b JOIN resq_runs AS r ON r.run_id = b.run_id
WHERE (:service = '' OR r.service = :service) AND (:environment = '' OR r.environment = :environment) ORDER BY r.finished_at, b.benchmark_id;

-- query:coverage_trend — Coverage basis/completeness
SELECT r.finished_at AS time, c.function_percent, c.line_percent,
       c.statement_site_percent, c.statement_site_instrumentation_percent,
       c.branch_percent, c.branch_instrumentation_percent
FROM resq_coverage_runs AS c JOIN resq_runs AS r ON r.run_id = c.run_id
WHERE (:service = '' OR r.service = :service) AND (:environment = '' OR r.environment = :environment) ORDER BY r.finished_at;

-- query:deployment_host — Branch/deployment/host correlation
SELECT r.finished_at AS time, r.service, r.environment, r.deployment_id,
       r.artifact_digest, r.vcs_sha, r.vcs_branch, r.hostname, r.q_version,
       r.os, r.ci_provider, r.ci_pipeline_id, r.fail_count, r.error_count
FROM resq_runs AS r WHERE (:service = '' OR r.service = :service) AND (:environment = '' OR r.environment = :environment) ORDER BY r.finished_at DESC;

-- query:coverage_context — Coverage by test context
SELECT r.finished_at AS time, c.context_id, c.test_id, t.status, m.kind,
       SUM(m.hits) AS hits
FROM resq_coverage_contexts AS c
JOIN resq_runs AS r ON r.run_id = c.run_id
LEFT JOIN resq_tests AS t ON t.run_id = c.run_id AND t.test_id = c.test_id
JOIN resq_coverage_context_metrics AS m
  ON m.coverage_context_key = c.coverage_context_key
WHERE (:service = '' OR r.service = :service) AND (:environment = '' OR r.environment = :environment)
GROUP BY r.finished_at, c.context_id, c.test_id, t.status, m.kind
ORDER BY r.finished_at, c.context_id, m.kind;
