.tst.desc["Transactional directory fixtures"]{
  should["restore the prior directory state when fixture loading fails"]{
    oldFs:.utl.fs;
    oldSnapshot:.utl.fsSnapshot;
    oldContext:.tst.context;
    oldCurrent:.tst.currentDirFixture;
    oldSaved:.tst.savedDir;
    oldAttemptAll:.tst.attemptAll;
    oldFinish:.tst.raiseAttemptFailuresWith;
    oldFind:.tst.findDirVars;
    oldClear:.tst.clearDirStateWith;
    oldBuilder:.tst.makeDirClear;
    oldEmpty:.tst.emptySavedDir;
    sentinel:([] v:enlist 42);
    .tst.fixtureDirectorySentinel:sentinel;
    .tst.context:`.tst;
    fake:.utl.fsSnapshot[];
    fake[`loadPath]:{[path]
      .tst.attemptAll:{[a;b;c]'"poisoned attempt-all"};
      .tst.raiseAttemptFailuresWith:{[a;b;c]'"poisoned finish"};
      .tst.findDirVars:{[]'"poisoned directory scan"};
      .tst.clearDirStateWith:{[a;b](::)};
      .tst.makeDirClear:{[]'"poisoned clear builder"};
      .tst.emptySavedDir:{[]'"poisoned empty state"};
      delete savedDir from `.tst;
      delete currentDirFixture from `.tst;
      '"forced directory fixture load failure"};
    .utl.fs:fake;
    .utl.fsSnapshot:{[].utl.fs};
    outcome:.[.tst.loadFixtureDir;
      ("/tmp/resq-fixture-transaction-failure";`);
      {[e]e}];
    `.tst.attemptAll set oldAttemptAll;
    `.tst.raiseAttemptFailuresWith set oldFinish;
    `.tst.findDirVars set oldFind;
    `.tst.clearDirStateWith set oldClear;
    `.tst.makeDirClear set oldBuilder;
    `.tst.emptySavedDir set oldEmpty;
    existsAfter:`fixtureDirectorySentinel in key `.tst;
    valueAfter:$[
      existsAfter;
      get `.tst.fixtureDirectorySentinel;
      ()];
    currentAfter:.tst.currentDirFixture;
    savedAfter:.tst.savedDir;
    `.utl.fs set oldFs;
    `.utl.fsSnapshot set oldSnapshot;
    `.tst.context set oldContext;
    if[not existsAfter;
      .tst.currentDirFixture:`recovery;
      @[.tst.restoreDir;();{[e](::)}]];
    if[`fixtureDirectorySentinel in key `.tst;
      ![`.tst;();0b;enlist `fixtureDirectorySentinel]];
    `.tst.currentDirFixture set oldCurrent;
    `.tst.savedDir set oldSaved;
    must[not (::)~outcome;"failed fixture load must signal"];
    existsAfter musteq 1b;
    valueAfter musteq sentinel;
    currentAfter musteq oldCurrent;
    savedAfter musteq oldSaved;
  };
};
