#!/usr/bin/env python3
"""Render or verify the SQL/Grafana examples from the executable contract."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from ingestion_contract import QUERY_BY_KEY, QUERIES, ddl_statements, query_sql


ROOT = Path(__file__).resolve().parents[1]
POSTGRES = ROOT / "docs/examples/resq_ingestion.sql"
SQLITE = ROOT / "docs/examples/resq_ingestion_sqlite.sql"
DASHBOARD = ROOT / "docs/examples/grafana-resq-overview.json"


def render_sql(dialect: str) -> str:
    header = [
        "-- Generated by tools/render_ingestion_assets.py; do not edit by hand.",
        "-- tools/ingestion_contract.py is the table, column, join, and query contract.",
    ]
    if dialect == "postgres":
        header += [
            "-- Reference psql variables for the queries below:",
            "\\set service 'orders'",
            "\\set environment 'test'",
        ]
    else:
        header += [
            "-- SQLite queries use named :service and :environment parameters.",
        ]
    body = [statement + ";" for statement in ddl_statements(dialect)]
    for query in QUERIES:
        body += ["", f"-- query:{query.key} — {query.title}", query_sql(query, "psql" if dialect == "postgres" else "sqlite") + ";"]
    return "\n".join([*header, "", *body, ""])


def render_dashboard() -> str:
    panels = []
    panel_keys = (
        "pass_fail_rate", "run_duration", "test_history", "benchmark_history",
        "coverage_trend", "deployment_host", "coverage_context",
    )
    for index, key in enumerate(panel_keys, start=1):
        query = QUERY_BY_KEY[key]
        panels.append({
            "id": index,
            "title": query.title,
            "type": query.panel_type,
            "datasource": {"type": "grafana-postgresql-datasource", "uid": "${DS_RESQ_SQL}"},
            "targets": [{
                "refId": "A", "format": "time_series" if query.panel_type == "timeseries" else "table",
                "rawQuery": True, "rawSql": query_sql(query, "grafana"),
            }],
            "gridPos": {"h": 8, "w": 12, "x": 0 if index % 2 else 12, "y": ((index - 1) // 2) * 8},
        })
    dashboard = {
        "title": "resQ SQL evidence overview",
        "description": "Executable SQL panels over the resQ normalized table-v2 ingestion path.",
        "schemaVersion": 39,
        "tags": ["resq", "testing", "sql"],
        "__inputs": [{
            "name": "DS_RESQ_SQL", "label": "resQ PostgreSQL", "type": "datasource",
            "pluginId": "grafana-postgresql-datasource", "pluginName": "PostgreSQL",
        }],
        "templating": {"list": [
            {
                "name": "service", "type": "query", "label": "Service",
                "datasource": {"type": "grafana-postgresql-datasource", "uid": "${DS_RESQ_SQL}"},
                "query": QUERY_BY_KEY["services"].sql, "refresh": 1,
            },
            {
                "name": "environment", "type": "query", "label": "Environment",
                "datasource": {"type": "grafana-postgresql-datasource", "uid": "${DS_RESQ_SQL}"},
                "query": query_sql(QUERY_BY_KEY["environments"], "grafana"), "refresh": 1,
            },
        ]},
        "panels": panels,
        "time": {"from": "now-30d", "to": "now"},
    }
    return json.dumps(dashboard, ensure_ascii=False, indent=2) + "\n"


def expected_assets() -> dict[Path, str]:
    return {
        POSTGRES: render_sql("postgres"),
        SQLITE: render_sql("sqlite"),
        DASHBOARD: render_dashboard(),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, expected in expected_assets().items():
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
        elif not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(path)
    if stale:
        print(
            "stale ingestion assets: " + ", ".join(str(path.relative_to(ROOT)) for path in stale)
            + "; run tools/render_ingestion_assets.py --write",
            file=sys.stderr,
        )
        return 1
    action = "updated" if args.write else "verified"
    print(f"{action} {len(expected_assets())} generated ingestion assets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
